version: '3'
services:
  demo:
    image: demo
    restart: always
    tty: true
    container_name: demo
    environment:
      TZ: Asia/Shanghai
      FDFS_TRACKER: 192.168.0.108
      WEB_SERVER: 127.0.0.1
      PROTOCOL: http
      WEB_PORT: 9999
      FDFS_PORT: 22122
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: demo
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      PROXY_HOST: host.docker.internal
      PROXY_PORT: 1080
    ports:
      - 8888:80
    volumes:
      - ~/demo/logs:/logs
    depends_on:
      - mysql
      - fastdfs

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    # 允许容器执行全部的系统调用
    security_opt:
      - seccomp:unconfined
    ports:
      - 3300:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quantization
    volumes:
      - ~/mysql:/var/lib/mysql

  fastdfs:
    image: qbanxiaoli/fastdfs
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: fastdfs
    environment:
      # nginx服务端口,默认80端口，可修改
      WEB_PORT: 9999
      # tracker_server服务端口，默认22122端口，可修改
      FDFS_PORT: 22122
      # fastdht服务端口，默认11411端口，可修改
      FDHT_PORT: 11411
      # docker所在宿主机的IP地址，默认使用eth0网卡的地址
      IP: 192.168.0.108
    volumes:
      # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
      - ~/fastdfs:/var/local
    # 网络模式为host，可不暴露端口，即直接使用宿主机的网络端口，只适用于linux系统
    network_mode: host

