server:
  port: 80
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  # 默认使用dev环境
  profiles:
    active: @spring.profiles.active@
    include:
      - wechat
      - security
      - mybatis
      - fastdfs
      - huobi
  # i18n configuration(添加语言国际化支持)
  messages:
    basename: i18n/messages
  # 时间处理
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS          默认
    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY       属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL        属性为NULL   不序列化
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  batch:
    job:
      # 程序加载的时候job默认都会执行，设置为false表示不执行
      enabled: false
  mail:
    host: smtp.qq.com
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          ssl:
            enable: true

# 设置代理，可翻墙调用
proxy:
  host: ${PROXY_HOST:127.0.0.1}
  port: ${PROXY_PORT:1080}

# 启用swagger文档
swagger:
  show: true

